create table if not exists public.recommendations (
  id bigint generated by default as identity primary key,
  parent_id bigint not null,
  tmdb_id bigint,
  media_type text not null default 'movie',
  title text not null,
  year integer,
  rating numeric default 0,
  votes integer not null default 1 check (votes >= 0),
  poster text,
  poster_path text,
  release_date text,
  user_id text,
  created_at timestamp with time zone not null default now()
);

alter table public.recommendations add column if not exists tmdb_id bigint;
alter table public.recommendations add column if not exists media_type text not null default 'movie';
alter table public.recommendations add column if not exists poster_path text;
alter table public.recommendations add column if not exists release_date text;
alter table public.recommendations add column if not exists user_id text;

create unique index if not exists recommendations_parent_tmdb_media_unique
on public.recommendations(parent_id, tmdb_id, media_type)
where tmdb_id is not null;

create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  user_id text not null,
  recommendation_id bigint not null references public.recommendations(id) on delete cascade,
  created_at timestamp with time zone not null default now(),
  unique (user_id, recommendation_id)
);

create unique index if not exists votes_user_recommendation_unique
on public.votes(user_id, recommendation_id);

alter table public.recommendations enable row level security;

drop policy if exists "Anyone can read recommendations" on public.recommendations;
create policy "Anyone can read recommendations"
on public.recommendations
for select
using (true);

drop policy if exists "Anyone can insert recommendations" on public.recommendations;
create policy "Anyone can insert recommendations"
on public.recommendations
for insert
with check (true);

drop policy if exists "Anyone can update recommendation votes" on public.recommendations;
create policy "Anyone can update recommendation votes"
on public.recommendations
for update
using (true)
with check (true);

drop policy if exists "Anyone can delete recommendations" on public.recommendations;
create policy "Anyone can delete recommendations"
on public.recommendations
for delete
using (true);

alter table public.votes enable row level security;

drop policy if exists "Anyone can read votes" on public.votes;
create policy "Anyone can read votes"
on public.votes
for select
using (true);

drop policy if exists "Anyone can insert votes" on public.votes;
create policy "Anyone can insert votes"
on public.votes
for insert
with check (true);
